title: Neighborhood Sounds
description: Making Music Happen. We organize shows and provide resources for artists in the Magic Valley area. Whether you're a music fan looking to explore the local scene, or an artist seeking to join the growing culture, we can show you where to go.
url: www.neighborhoodsounds.com
author: Jordan Thornquest
logo: /img/logo.png
google_site_verification: Hka8oNAX51XY-SN7OaraTQlMOzUX38QmY7c0OW8lDYc
facebook:
  app_id: 1354548861311532
twitter:
  username: neibohoodsounds
social:
  name: Neighborhood Sounds
  links:
    - https://twitter.com/neibohoodsounds
    - https://www.facebook.com/neighborhoodsounds
    - https://instagram.com/neighborhoodsounds

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
